name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        
    - name: Build Backend
      run: |
        cd backend
        npm run build
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
        
    - name: Run Backend Tests
      run: |
        cd backend
        npm test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} 